FROM php:7.3-alpine

Maintainer Support <support@etechfocus.com>

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer 
RUN apk add --no-cache openssh-client ca-certificates bash
